version: "3.7"
services:
  backend:
    build:
      context: .
    image: 705373246515.dkr.ecr.ap-northeast-2.amazonaws.com/consumer:1.0.1
    environment:
      KAFKA_HOST_0: host0
      KAFKA_HOST_1: host1
      KAFKA_HOST_2: host2
      AWS_ACCESS_KEY_ID: your_access
      AWS_SECRET_ACCESS_KEY: your_secret
      AWS_DEFAULT_REGION: ap-northeast-2
      KAFKA_TOPIC: scraping
      KAFKA_OFFSET_RESET: earliest